[project]
name = "meta-hack-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "fastapi==0.95.2",
    "uvicorn==0.22.0",
    "pydantic==1.10.7",
    "requests==2.31.0",
    "python-dotenv==1.0.0",
    "llama-index",
    "llama-index-readers-file",
    "sentence-transformers",
    "faiss-gpu-cu12",
    "llama-api-client>=0.1.1",
    "ollama",
    "fastkml",
    "openpyxl>=3.1.5",
]
